appTwo/urls.py
from django.conf.urls import url
from appTwo import views

app_name = 'appTwo'

urlpatterns = [
	url(r'^$', views.users, name = 'users'),
	url(r'^list', views.index, name = 'users_list'),
]

first_app/urls.py
from django.conf.urls import url
from first_app import views 

app_name = 'first_app'

urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^register/$', views.register,name='register'),
	url(r'^user_login/$', views.user_login, name="user_login"),
]

first_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from first_app import views
from appTwo import views as appTwoViews

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^first_app/', include('first_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^formpage', views.form_name_view, name="form_name"),
    url(r'^users/', include('appTwo.urls')),
    url(r'^logout/$', views.user_logout,name='logout'),
    url(r'^special/', views.special,name='special'),
]

appTwo/models.py
from django.db import models

# Create your models here.

class User(models.Model):
	first_name = models.CharField(max_length=264)
	last_name = models.CharField(max_length=264)
	email = models.EmailField(max_length=264, unique=True)

	def __str__(self):
		return self.first_name+' '+self.last_name

first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
	top_name = models.CharField(max_length=264,unique=True)

	def __str__(self):
		return self.top_name

class Webpage(models.Model):
	topic = models.ForeignKey(Topic)
	name = models.CharField(max_length=264,unique=True)
	url = models.URLField(unique=True)

	def __str__(self):
		#return self.name
		return self.name

class AccessRecord(models.Model):
	name = models.ForeignKey(Webpage)
	date = models.DateField()

	def __str__(self):
		return str(self.date)				

class UserProfileInfo(models.Model):
	user = models.OneToOneField(User)

	#additional
	
	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

	def __str__(self):
		return str(self.user.username)

appTwo/forms.py
from django import forms
from appTwo.models import User

class NewUserForm(forms.ModelForm):
	class Meta():
		model = User 
		fields = '__all__'

first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

def check_for_z(value):
	if value[0].lower() != 'z':
		raise forms.ValidationError('NAME MUST START WITH THE LETTER Z!')

class FormName(forms.Form):
	name = forms.CharField(validators=[check_for_z])
	email = forms.EmailField()
	verifyemail = forms.EmailField(label="Enter your email again")
	text = forms.CharField(widget=forms.Textarea)
	botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

	# def clean_botcatcher(self):
	# 	botcatcher = self.cleaned_data['botcatcher']

	# 	if len(botcatcher) > 0:
	# 		raise forms.ValidationError("GOTCHA BOT!")
	# 	return botcatcher	

	def clean(self):
		all_clean_data = super().clean()
		email = all_clean_data['email']
		vemail = all_clean_data['verifyemail']

		if email != vemail:
			raise forms.ValidationError("MAKE SURE EMAILS MATCH")


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo

		fields = ('portfolio_site', 'profile_pic')


				

appTwo/views.py
from django.shortcuts import render
#from django.http import HttpResponse
from appTwo.models import User
from appTwo.forms import NewUserForm


# Create your views here.

def index(request):
	users = User.objects.order_by('first_name')

	return render(request, 'appTwo/index.html', {'users': users})

def users(request):
	form = NewUserForm()

	if request.method == "POST":
		form = NewUserForm(request.POST)

		if form.is_valid():
			form.save(commit=True)
			return index(request)
		else:
			print('ERROR: FORM INVALID')	

	return render(request, 'appTwo/users.html', {'form': form})		

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
import os
from first_app.models import Topic,Webpage,AccessRecord
from pprint import pprint
from first_app.forms import FormName,UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
	webpages_list = AccessRecord.objects.order_by('date')

	pprint(webpages_list[0].name)

	my_dict = {
		'insert_me': "Hello! I am from first_app/views.py!",
		'access_records': webpages_list,
		'number': 100,
		'name': 'zubaer ahammed'
	}

	return render(request, 'first_app/index.html', context=my_dict)


def form_name_view(request):
	form = FormName()

	if request.method == 'POST':

		form = FormName(request.POST)

		if form.is_valid():
			print("Validation Successful!")
			print("Name: "+form.cleaned_data['name'])
			print("Email: "+form.cleaned_data['email'])
			print("Text: "+form.cleaned_data['text'])


	return render(request, 'first_app/form_page.html', {'form': form} )


def register(request):

	registered = False

	if request.method == 'POST':
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit = False)
			profile.user = user

			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']

			profile.save()
			
			registered = True
		else:
			print(user_form.errors,profile_form.errors)

	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm()

	return render(request, 'first_app/registration.html', 
				{
					'user_form': user_form, 
					'profile_form': profile_form,
					'registered': registered
				})


def user_login(request):
	
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('index'))
			else:
				return HttpResponse("ACCOUNT NOT ACTIVE")
		else:
			print("Someone tried to login and failed!")
			print("Username: {} and password: {}".format(username,password))
			return HttpResponse("Invalid login details supplied!")
	else:
		return render(request,'first_app/login.html',{})


@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
	return HttpResponse("You are logged in, Nice!")

templates/appTwo/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Hello there!</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
</head>
<body>

	<div class="container">
		

		{% if user %}

			<h1>Username: {{ user.username }}</h1>

		{% endif %}

		<a href="{% url 'appTwo:users' %}">You can sign up from here</a>

		<div class="access_records">
			
			{% if users %}
			
				<table>
					<thead>
						<th>Site Name</th>
						<th>Date Accessed</th>
					</thead>

					<tbody>
							
						{% for user in users %}
							<tr>
								<td>{{ user.first_name }}</td>
								<td>{{ user.email }}</td>
							</tr>
						{% endfor %}	

					</tbody>

				</table>

			{% else %}
				<p>NO USERS RECORD FOUND!</p>
			{% endif %}

		</div>
		

	</div>


</body>
</html>

templates/appTwo/users.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Form Page</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
</head>
<body>
	
	<div class="container">
		
		{% if user %}

			<h1>Username: {{ user.username }}</h1>

		{% endif %}
		
		<a href="{% url 'appTwo:users_list' %}">See all users list</a>

		<form method="POST">
			
			{% csrf_token %}	
			
			{{ form.as_p }}

			<input type="submit" class="btn btn-primary" value="Submit">
			
		</form>

	</div>

</body>
</html>

templates/first_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Hello there!</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
</head>
<body>

	<nav class="navbar navbar-default">
	  <div class="container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">First Project</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Brand</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="{% url 'index' %}">Home</a></li>
	        <li><a href="{% url 'admin:index' %}">Admin</a></li>
	        <li><a href="{% url 'appTwo:users' %}">appTwo Users</a></li>
	        <li><a href="{% url 'first_app:register' %}">Register</a></li>

			{% if user.is_authenticated %}
				<li><a href="{% url 'logout' %}">Logout</a></li>
			{% else %}
				<li><a href="{% url 'first_app:user_login' %}">Login</a></li>
			{% endif %}

	      </ul>


	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<div class="container">
		
		
		{% if user %}

			<h1>Username: {{ user.username }}</h1>

		{% endif %}

		{% block body_block %}
		<!-- Anything outside of this block will be inherited if you extend this template -->
		{% endblock %}

	</div>


</body>
</html>

templates/first_app/form_page.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}

	{% block body_block %}	
		<form method="POST">
			
			{% csrf_token %}	
			
			{{ form.as_p }}

			<input type="submit" class="btn btn-primary" value="Submit">
			
		</form>
	{% endblock %}	

templates/first_app/index.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% load staticfiles %}
{% load my_extras %}

	{% block body_block %}	


		<h1>Hello! This is first_app/index.html</h1>
		{{ insert_me }}	


		<h1>{{ name | upper }}</h1>
		<h1>{{ name | cut_string:"ahammed" }}</h1>
		<h1>{{ number | add:"99" }}</h1>

		<img src="{% static 'images/Aqua.png' %}" alt="EBL Aqua Card Info">

		<h2>Here are your Website Access Records:</h2>

		
		<h2><a href="{% url 'form_name' %}">Go to the /formpage to fill out the form</a></h2>


		<h1><a href="{% url 'admin:index' %}">Go to the Admin Panel</a></h1>

		<div class="access_records">
			
			{% if access_records %}
			
				<table>
					<thead>
						<th>Site Name</th>
						<th>Date Accessed</th>
					</thead>

					<tbody>
							
						{% for acc in access_records %}
							<tr>
								<td>{{ acc.name }}</td>
								<td>{{ acc.date }}</td>
							</tr>
						{% endfor %}	

					</tbody>

				</table>

			{% else %}
				<p>NO ACCESS RECORD FOUND!</p>
			{% endif %}

		</div>

	{% endblock %}	
		

templates/first_app/login.html
{% extends 'first_app/base.html' %}

{% block body_block %}

	<div class="jumbotron">
		
		<h1>Please Login</h1>

		<form action="{% url 'first_app:user_login' %}" method="post">
			
			{% csrf_token %}

			<label for="username">Username:</label>
			<input type="text" name="username" placeholder="Enter Username">

			<label for="username">Password:</label>
			<input type="password" name="password">

			<input type="submit" value="Login">

		</form>

	</div>

{% endblock %}

templates/first_app/registration.html
{% extends 'first_app/base.html' %}

{% load staticfiles %}

{% block body_block %}

	<div class="jumbotron">
		
	{% if registered %}
	
		<h1>Thank you for registering!</h1>

	{% else %}
	
		<h1>Register here!</h1>
		<h3>Fill out the form:</h3>

		<form enctype="multipart/form-data" method="post">
			
			{% csrf_token %}
			{{ user_form.as_p }}
			{{ profile_form.as_p }}
			<input type="submit" name="" value="Register">


		</form>

	{% endif %}
		
	</div>

{% endblock %}